# Generated by Django 5.0.3 on 2024-03-09 14:16

import django.core.validators
import django.db.models.deletion
import django.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Archived', 'Archived')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(default=django.utils.crypto.get_random_string, max_length=32, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Password must contain at least one uppercase letter, one number, and one special character.', regex='^(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%^&*()_+{}|:"<>?`\\-=[\\]\\;\',./])')])),
            ],
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='justdoit.user'),
        ),
    ]
