# Generated by Django 5.0.3 on 2024-03-09 14:30

import justdoit.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0002_task_user_delete_tasks_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=justdoit.utils.uuid, max_length=32, primary_key=True, serialize=False),
        ),
    ]
