# Generated by Django 5.0.3 on 2024-03-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0004_alter_task_creation_time_alter_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(auto_created=True, default='0m3YIrdWNnGZ4UPoQi6Bp8HFjIzaukdwnFTQCHY6TUtkRGMWNP', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
