# Generated by Django 5.0.3 on 2024-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0005_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(auto_created=True, default='l8EmJbmuwNGqT5O1oldYkRmSSYeo7kfEV9WRaNJWQCb0dQes87', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
