# Generated by Django 5.0.3 on 2024-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0007_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(auto_created=True, default='jzpIBdanAQcddsIJN4llT5YLwTLysCZBlIHTAcaS0txaudv7ce', max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
