# Generated by Django 5.0.3 on 2024-03-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('justdoit', '0010_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(default='tvqh1eoxYvDFsX94UVjyhPArbjnZY8PLZTyxuU4StVUzyxFn3I', max_length=50, primary_key=True, serialize=False),
        ),
    ]
